export const diabetesText = {
  home: {
    title: 'Diabetes & DKA',
    diagnostic: 'Diagnostic',
    diabetesDiagnosis: 'Diabetes Diagnosis',
    diabeticKetoacidosis: 'Diabetic Ketoacidosis (DKA) Diagnosis',
    cerebralEdema: 'Cerebral Edema Diagnosis',
    treatment: "Treatment",
    initialDKATreatment: 'Initial DKA Treatment',
    dkaInsulin: 'DKA Insulin Drip/IVF Titration',
    cerebralEdemaTreatment: 'Cerebral Edema Treatment',
    routineInsulineDosing: 'Routine (non-DKA) Insulin Dosing',
    other: 'Other',
    pumpMalfunction: 'Suspected Pump Malfunction',
    disclaimer: "Disclaimer: ",
    disclaimerStart: 'These guides are designed to direct ',
    disclaimerItalic: 'initial ',
    disclaimerFinish: 'diabetes therapy in known and new-onset diagnoses. Consultation with a Pediatric Endocrinologist is recommended for ongoing management.'
  },
  diabetesDiagnosis: {
    type1: 'Type 1 Diabetes',
    type2: 'Type 2 Diabetes',
    gestationalDiabetes: 'Gestational Diabetes',
    lessCommonDiabetesDiagnoses: 'Less Common Diabetes Diagnoses',
    type1Details: 'Autoimmune destruction of pancreatic beta-cells leading to absolute insulin deficiency.',
    type2Details: 'Progressive ineffective use of insulin, resulting in high insulin production and insulin resistance.',
    gestationalDetails: 'Diabetes associated with pregnancy that is typically diagnosed in the second or third trimester.',
    lessCommonDetails: 'Autoimmune destruction of pancreatic beta-cells leading to absolute insulin deficiency. These include genetic and medication induced forms of diabetes.',
    decisionSupport: 'Diagnosis Decision Support'
  },
  diagnosisSupport: {
    laboratoryTesting: 'Laboratory Testing ',
    selectAllThatApply: '(select all that apply)',
    note: 'Note: ',
    laboratoryNote: 'Point of care testing may NOT be used for diagnosis',
    signsAndSymptoms: 'Signs & Symptoms ',
    criteriaMet: 'Criteria met',
    criteriaNotMet: 'Criteria not met',
    home: "Diabetes & DKA Home"
  },
  ketoacidosis: {
    title: 'Diabetes Ketoacidosis Diagnosis',
    question: 'Is the patient exhibiting critical organ instability?',
    yes: 'Yes',
    no: 'No',
    resusRedirectTitle: 'Provide Appropriate Stabilization Care per PALS',
    resusRedirectButton: 'Resuscitation: Emergency Life Support and Burn Fluid Management',
    secondQuestion: 'Does the patient have a known diabetes diagnosis?'
  },
  recommendations: {
    onsetType1: 'Recommendations for New Onset Type 1',
    type1: 'Recommendations for Type 1 Diabetes',
    nextLaboratoryResults: 'Next: Laboratory Results'
  },
  laboratoryResults: {
    title: 'Laboratory Results',
    question: 'What were the patient’s lab results?',
    needLabs: 'Need labs to proceed',
    dkaLikely: "DKA Likely",
    dkaNotLikely: 'DKA Not Likely',
    dkaNotLikelySubinfo: 'Consider Alternative Diagnosis',
    correctionDose: 'Correction dose needed'
  },
  dkaTreatment: {
    title: "Tell us something about the patient",
    dkaTitle: 'Diagnosis',
    proceed: 'Proceed to treatment',
    warningTitle: "The patient is in Diabetic Ketoacidosis!",
    warningInfo: "To see treatment options, enter patient's age and weight:",
    ageAndWeight: "What is the patient's age and weight?",
    treatmentTitle: 'Diabetic Ketoacidosis Treatment',
    treatmentSectionHeader: 'Key Considerations',
    recommendation: 'Recommendation',
    recommendationInfo: 'Patients be NPO during treatment, but may be allowed ice chips or small drinks of water',
    next: 'Next: IV Fluids',
    iDontKnow: "I don't know the age & weight",
    ageWarning: 'This clinical module is not appropriate for caring for patients under 2 years of age or under 10kg'
  },
  cerebralEdema: {
    title: 'Cerebral Edema',
    question: "Is the patient exhibiting the signs or symptoms of Cerebral Edema?",
    needToDiagnose: 'Need to diagnose the patient for Cerebral Edema?',
    diagnosisAssistant: "Start Cerebral Edema Diagnosis Assistant",
    cerebralTreatment: "Proceed to Cerebral Edema Treatment",
    dkaTreatment: 'Proceed to DKA Treatment',
    cerebralTreatmentTitle: 'Cerebral Edema Treatment',
    warning: 'Begin treatment immediately if Cerebral Edema is suspected',
    bedsideMeasures: "Bedside Measures",
    pharmacologicTherapy: 'Pharmacologic Therapy',
    pharmacologicSubtitle: 'Which is readily available at your institution?',
    imagingStudies: 'Imaging Studies',
    imagingStudiesSubtitle: 'Obtain CT Head after starting treatment to evaluate for other causes of increased intracranial pressure',
    disposition: 'Disposition',
    dispositionSubtitle: 'Admit to Pediatric Intensive Care Unit',
    next: 'Next: DKA Treatment'
  },
  ivFluids: {
    title: 'IV Fluids',
    recommendations: "Recommendations",
    recommendationsInfo: 'Administer 10 mL/kg IV Fluid bolus of Normal Saline over 1-2 hours (max 1000 mL)',
    next: 'Next: Insulin',
    suggestedVolume: 'Suggested Volume - ',
    max: 'Max of 1000ml',
    followBolus: 'Follow bolus with IVF at 1.5x maintenance',
    maintanenceRate: 'Maintenance Rate - ',
    moreMaintananceRate: '1.5x Maintenance Rate - ',
    twoIVF: 'Two IVF bags “Y’d” together are recommended to achieve variable glucose infusion rates',
    recommendBothBags: 'Recommend both bags have the following potassium additives (added once kidney function is confirmed)',
  },
  insulin: {
    title: 'Insulin',
    sectionTitle: 'Is the patient using an insulin pump?',
    next: 'Next: Basal Insulin',
    warning: "Remove insulin pump (infusion site) from patient's body"
  },
  pumpMalfunction: {
    title: 'Pump Malfunction',
    sectionTitle: 'Insulin pumps only deliver RAPID acting insulin. Any interruption in pump delivery may result in DKA.',
    subtitle: 'If pump is not working:',
    navigatingSettings: 'Navigating Pump Settings',
    dosingInsulin: 'Dosing Insulin Now',
    suspectedDKA: 'Suspected DKA',
    settingsInfo: 'Given the complexity of these devices, consider consultation with Pediatric Endocrinologist before manipulating pump.\n\nParent/Guardian and/or patient are excellent resources to navigate pump settings.',
    medtronic: 'Medtronic',
    tandem: 'Tandem (t:slim)',
    insulet: 'Insulet (Omnipod)'
  },
  basalInsulin: {
    title: 'Basal Insulin',
    next: 'Next: Ondansetron'
  },
  ondansetron: {
    title: 'Ondansetron',
    next: 'Next: Insulin Drip'
  },
  insulinDrip: {
    title: "Insulin Drip",
    next: 'Next: Insulin Drip & IVF Titration',
    titrationTitle: 'Insulin Drip & IVF Titration',
    enterBG: 'Enter current BG',
    dkaResolved: "DKA Likely Resolved",
    infoText: 'Consider d/c insulin drip and dextrose containing IVF',
    maxGlucose: 'Please consult an endocrinologist for recommendations',
    backToTitration: 'Back to Titration'
  },
  hypoglycemia: {
    title: 'Hypoglycemia Management',
    cardTitle: 'Suggested Treatment Rates',
    nsBag: 'NS Bag Rate',
    d10Bag: 'D10 Bag Rate',
    finalConcentration: 'Final Dextrose Concentration',
    furtherInstructions: 'Further Instructions'
  },
  titrationRates: {
    title: 'Insulin Drip & IVF Titration',
    regularInsulin: 'Regular Insulin Rates',
    regulatInsulinHint: 'For patient who have a BG < 80 mg/dL on drip'
  },
  cerebralEdemaDiagnosis: {
    title: 'Diagnostic Criteria',
    bottomText: 'Cerebral Edema Diagnosis',
    cerebralEdemaLikely: 'Cerebral Edema Likely',
    cerebralEdemaNotLikely: 'Cerebral Edema Not Likely',
    majorCriteria: 'Major Criteria',
    minorCriteria: 'Minor Criteria',
    criteriaNotMet: 'Criteria Not Met',
    diagnosis: 'Diagnosis',
    cerebralEdemaLikelyWarning: 'Cerebral Edema is likely, begin treatment immediately.',
    likelyWarningInfo: 'Do not wait for imaging studies to begin treatment.',
    treatmentRecommendations: 'Treatment Recommendations',
    diagnosticCriteriaMet: 'Diagnosis Criteria Met',
    diagnostic: 'Diagnostic',
    major: "Major",
    minor: 'Minor',
    notLikelyTitle: 'Cerebral Edema is not likely at this time.',
    notLikelyInfo: 'Continue to monitor for the Cerebral Edema during the course of DKA treatment.',
    nextDKA: 'Next: DKA Treatment'
  },
  rapidInsulin: {
    title: 'Routine Rapid Acting Insulin Dosing',
    isPatientOnInsulinPump: 'Is the patient on an insulin pump?',
    doYouHaveAccessToDosing: "Do you have access to the patient's usual dosing regimen?",
    isPumpWorking: 'Is the pump suspected to be working normally?',
    areKetonesPresent: 'Are moderate or large ketones present?',
    isThePatientAboutToEat: 'Is the patient about to eat?',
    glucoseTitle: "What is the patient's glucose level?",
    calculateDosage: 'Calculate dosage using the patient’s pump',
    usePump: 'Use pump to calculate and deliver appropriate dose by entering BG and carb intake',
    itWillCalculate: 'It will calculate and deliver a bolus of insulin based on the patient’s unique settings',
    bloodKetones: `POC Blood Ketones,\n< 0.6 mmol/L: Negative,\n0.6 to 1.4 mmol/L: Moderate,\n>/ 1.5 mmol/L:  Large`,
    insulinDose: "What is the patient's daily dose of insulin",
    totalDailyDose: "Total Daily Dose",
    totalDoseInfo: 'Total number of units of insulin used, on average, each day. This includes both bolus and basal insulins',
    ketoneLevel: "Ketone Level",
    moderate: 'Moderate',
    large: 'Large',
    doseForKetones: 'Dose for Ketones',
    treatmentConsiderations: 'Treatment Considerations',
    proceedToDka: 'Proceed to DKA Module',
    caution: "CAUTION: ",
    warning: 'Doses may need to be adjusted based on clinical situation. Consultation with a pediatric endocrinologist is recommended.',
    tellUsSomething: 'Tell us something about the patient',
    select: "Select",
    carbRatio: 'Carb Ratio (for current time of day)',
    carbInfo: 'The number of carbohydrates covered by one unit of rapid acting insulin',
    carbInfoTitle: 'Carb Ratio',
    carbohydrate: 'Carbohydrate count of food\nto be consumed',
    carbohydrateInfo: 'Total number of carbohydrates to be consumed, recorded in grams',
    carbohydrateInfoTitle: 'Carb Ratio',
    carbDose: 'Dose of rapid acting insulin to administer',
    carbDoseInfo: 'Total number of units of insulin used, on average, each day. This includes both bolus and basal insulins',
    carbDoseInfoTitle: 'Total Daily Dose',
    acknowledge: 'Acknowledge & Proceed',
    noAction: 'No action necessary',
    noActionInfo: 'Blood Glucose in target. No insulin administration is indicated at this time. Continue routine Blood Glucose monitoring',
    currentBG: 'Current BG',
    curretnBGInfo: 'BG obtained by either POC finger stick, or BG as reported by Continuous Glucose Monitor. Do not use info more than 30 minutes old',
    currentBGInfoTitle: 'Current Blood Glucose',
    targetBG: 'Target BG',
    targetBGInfoTitle: 'Target Blood Glucose',
    targetBGInfo: 'Typically 100 to 120 mg/dL. For young children, very active children, or those prone to hypoglycemia, the target may be higher',
    threeHours: 'Has it been > 3 hours since a dose of\ninsulin was given for HIGH glucose?',
    activeInsulinTime: 'Active Insulin Time',
    activeInsulinInfo: 'Length of time insulin is expected to continue working in circulation. Typically this is 3 hours',
    inulinSensetivity: 'Insulin Sensitivity Factor (ISF)',
    inulinSensetivityInfoTitle: 'Insulin Sensitivity Factor',
    inulinSensetivityInfo: 'The number of mg/dL one unit of rapid acting insulin is suspected to drop BG',
    rapidInsulin: 'Rapid Acting Insulin',
    rapidInsulinInfo: 'Insulins with onset of action of approximately 10-15 minutes, and duration of action of approximately 3-4 hours',
    warningInsulin: 'Previous dose of insulin is likely still active. Consider consultation with pediatric endocrinologist',
  }
}
