export const primaryColor = '#0D5EB6';
export const secondaryColor = '#2085FA';
export const whiteColor = '#ffffff';
export const transparentBlack = 'rgba(0, 0, 0, 0.3)';
export const grayColor = '#7C7C7C';
export const darkGray = '#3d3d3d';
export const lightGray = 'rgba(0, 0, 0, 0.2)';
export const blackColor = '#000000';
export const primaryColorOpaque = '#E4EFFA';
export const pinkColor = '#BF30B7'
export const lightBlueColor = '#EBEDF7'
export const mildAntibioticsColor = '#FFDF59';
export const strongAntibioticsColor = '#FFA20A'
export const emergencyColor = "#FF0000"
export const greenColor = "#4aac1b"
export const yellowColor = "#FFFF8A"