export const brueText = {
  title: 'BRUE Characterization',
  info: 'Please indicate whether the following are true:',
  notABrue: "Not a BRUE",
  notABrueInfoFirst: 'You have indicated that there is an explanation for the event:',
  notABrueInfoSecond: 'The patient has persistent symptoms, diagnostic exam findings, or an underlying diagnosis which therefore excludes BRUE. A BRUE diagnosis only applies to resolved events.',
  recommendation: 'Recommendation:',
  notABrueRecommendation: 'Evaluate and manage child based on persistent signs and symptoms and treat accordingly',
  secondStepInfo: 'Did the event include any to the following?',
  thirdStepInfo: 'After thorough history and physical, are any of the following conditions an explanation for the event?',
  exclutionTitle: 'BRUE Exclusion Criteria',
  briefResolvedTitle: 'BRUE: Brief Resolved Unexplained Event',
  fourthStepInfo: 'Does child have any of the following?',
  possibleDiagnosis: 'Possible BRUE Diagnosis',
  positiveRecommendation: "Determine the child's risk of BRUE diagnosis and review treatment recommendations.",
  negativeRecommendation: 'May need to re-evaluate child\'s history, signs and symptoms for alternative diagnosis.',
  startRiskClassification: 'Start Risk Classification',
  riskClassification: 'BRUE Diagnosis Risk Classification',
  selectAge: 'Select a gestational age:',
  highRiskClassifications: 'High Risk BRUE Pathways',
  whatPracticeSetting: 'What practice setting are you in?',
  ambulatoryEvaluation: 'Ambulatory Evaluation',
  ambulatoryEvaluationInfo: 'Proceed to initial management and evaluation in an ambulatory setting.​',
  inpatientEvaluation: 'Inpatient Evaluation',
  inpatientEvaluationInfo: 'Proceed to initial management and evaluation in an inpatient setting.',
  highRiskAmbulatory: 'BRUE High Risk Ambulatory Evaluation',
  highRiskAmbulatoryInfo: 'If the following evaluations are not available, consider hospital admission',
  newDiagnosis: 'New Diagnosis Established?',
  yes: "Yes",
  no: 'No, consider admission',
  diagnosis: "Diagnosis",
  highRiskBrue: "High Risk BRUE",
  highRiskRecommendation: 'Admit to hospital for further observation and evaluation',
  highRiskInpatient: 'BRUE High Risk Inpatient Initial Management and Evaluation Recommendations',
  noProceedToHospital: 'No: proceed to ongoing hospital course evaluation',
  highRiskOngoing: 'BRUE High Risk Ongoing Hospital Evaluation',
  regularNo: "No",
  finalQuestion: 'Has the patient had a repeat event?',
  suggestions: 'Suggestions',
  suggestionsInfo: 'If patient has had a repeat event, this suggests that there may be an underlying diagnosis that has not yet been established. Careful consideration for ongoing monitoring and further workup should be considered based on the event prior to discharge.',
  lowRiskRecommendations: 'BRUE Low Risk Recommendations'
}