export const RESUS_HOME = 'Resuscitation';
export const NEWLY_BORN_INFANT_INPUTS = 'Newly Born Infant Input';
export const NEWLY_BORN_INFANT_HOME = 'Newly Born Infant';
export const AIRWAY_AND_BREATHING = 'Airway and Breathing';
export const COMPRESSIONS = 'Compressions';
export const DRUG_DOSING = 'Drug Dosing';
export const MEDICATIONS_AND_FLUIDS = 'Medications and Fluids';
export const WEIGHT_INPUT = 'Patient Weight'
export const COLOR_INPUT = 'Length Based Tape Color'
export const PATIENT_DETAILS = 'Patient Details';
export const AGE_INPUT = 'Patient Age';
export const RESUS_PATHWAYS = 'Resus Pathways';
export const BASIC_LIFE_SUPPORT = 'Basic Life Support';
export const EQUIPMENT_SIZES = 'Equipment Sizes';
export const ADVANCED_LIFE_SUPPORT = 'Advanced Life Support';
export const CIRCULATION = 'Circulation'
export const ELECTRICAL_THERAPY = 'Electrical Therapy';
export const BURN_MANAGEMENT = 'Burn Management';
export const VITAL_SIGNS = 'Vital Signs & Assessments';