export const DIABETES_HOME = 'Diabetes & DKA'
export const DIABETES_DIAGNOSIS_PATHWAY = 'Diabetes Diagnosis Pathway';
export const DIAGNOSIS_DECISION_SUPPORT = 'Diagnosis Decision Support';
export const DIABETES_KETOACIDOSIS_DIAGNOSIS = 'Diabetes Ketoacidosis Diagnosis';
export const DIABETES_RESUS_REDIRECT = 'Diabetes Resus Redirect';
export const DIABETES_KETOACIDOSIS_SECOND = 'Diabetes Ketoacidosis Second';
export const RECOMMENDATIONS_FOR_NEW_ONSET = 'Recommendations For New Onset';
export const RECOMMENDATIONS_FOR_TYPE_1 = 'Recommendations For Type 1';
export const LABORATORY_RESULTS = 'Diabetes Laboratory Results';
export const PAITENT_INFO_INPUT = 'Patient Info Input';
export const CEREBRAL_EDEMA = 'Cerebral Edema';
export const CEREBRAL_EDEMA_TREATMENT = 'Cerebral Edema Treatment';
export const DIABETIC_KETOACIDOSIS_TREATMENT = 'Diabetic Ketoacidosis Treatment';
export const IV_FLUIDS = 'IV Fluids';
export const INSULIN_QUESTION = 'Insulin Question';
export const PUMP_MALFUNCTION = 'Pump Malfunction';
export const NAVIGATING_PUMP_SETTINGS = 'Navigating Pump Settings';
export const BASAL_INSULIN = 'Basal Insulin';
export const ONDANSETRON = 'Ondansetron'
export const INSULIN_DRIP = 'Insulin Drip';
export const INSULIN_DRIP_AND_TITRATION = 'Insulin Drip And IVF Titration';
export const HYPOGLYSEMIA_MANAGEMENT = 'Hypoglycemia Management'
export const TITRATION_RATES = 'Titration Rates'
export const CEREBRAL_EDEMA_DIAGNOSIS = 'Cerebral Edema Diagnosis';
export const CEREBRAL_EDEMA_MAJOR_CRITERIA = 'Cerebral Edema Major Criteria';
export const CEREBRAL_EDEMA_MINOR_CRITERIA = 'Cerebral Edema Minor Criteria';
export const ROUTINE_RAPID_INSULIN_DOING = 'Routine Rapid Insulin Dosing';
export const ROUTINE_INSULIN_PUMP_WORKING = 'Routine Insulin Pump Working';
export const ROUTINE_INSULIN_HAVE_ACCESS = 'Routine Insulin Have Access';
export const ROUTINE_INSULIN_GLUCOSE = 'Routine Insulin Glucose';
export const ROUTINE_INSULIN_FINISH = 'Routine Insulin Finish';
export const ROUTINE_INSULIN_KETONES = 'Routine Insulin Ketones';
export const ROUTINE_INSULIN_DOSE = 'Routine Insulin Dose';
export const ROUTINE_INSULIN_KETONES_DOSAGE = 'Routine Insulin Ketones Dosage';
export const ROUTINE_INSULIN_PATIENT_INFO = 'Routine Insulin Patient Info';
export const ROUTINE_INSULIN_ABOUT_TO_EAT = 'Routine Insulin About To Eat';
export const ROUTINE_INSULIN_CARB_RATIO = 'Routine Insulin Carb Ratio';
export const ROUTINE_INSULIN_CARB_3_HOURS = 'Routine Insulin Carb 3 Hours';
export const CEREBRAL_EDEMA_LIKELY = 'Cerebral Edema Likely';
export const CEREBRAL_EDEMA_NOT_LIKELY = 'Cerebral Edema Not Likely';
export const HYPOGLYCEMIA_MANAGEMENT_GLUCOSE = 'Hypoglycemia Management Glucose';
export const ROUTINE_INSULIN_NO_ACTION = 'Routine Insulin No Action';

export const DIABETES_TITLE_MAPPING = {
  [DIABETES_DIAGNOSIS_PATHWAY]: DIABETES_HOME,
  [DIAGNOSIS_DECISION_SUPPORT]: DIABETES_HOME,
  [DIABETES_KETOACIDOSIS_DIAGNOSIS]: DIABETES_HOME,
  [DIABETES_RESUS_REDIRECT]: DIABETES_HOME,
  [DIABETES_KETOACIDOSIS_SECOND]: DIABETES_HOME,
  [RECOMMENDATIONS_FOR_NEW_ONSET]: DIABETES_HOME,
  [RECOMMENDATIONS_FOR_TYPE_1]: DIABETES_HOME,
  [LABORATORY_RESULTS]: DIABETES_HOME,
  [PAITENT_INFO_INPUT]: DIABETES_HOME,
  [CEREBRAL_EDEMA]: DIABETES_HOME,
  [CEREBRAL_EDEMA_TREATMENT]: DIABETES_HOME,
  [DIABETIC_KETOACIDOSIS_TREATMENT]: DIABETES_HOME,
  [IV_FLUIDS]: DIABETES_HOME,
  [INSULIN_QUESTION]: DIABETES_HOME,
  [PUMP_MALFUNCTION]: DIABETES_HOME,
  [NAVIGATING_PUMP_SETTINGS]: DIABETES_HOME,
  [BASAL_INSULIN]: DIABETES_HOME,
  [ONDANSETRON]: DIABETES_HOME,
  [INSULIN_DRIP]: DIABETES_HOME,
  [INSULIN_DRIP_AND_TITRATION]: DIABETES_HOME,
  [HYPOGLYSEMIA_MANAGEMENT]: DIABETES_HOME,
  [TITRATION_RATES]: DIABETES_HOME,
  [CEREBRAL_EDEMA_DIAGNOSIS]: DIABETES_HOME,
  [CEREBRAL_EDEMA_MAJOR_CRITERIA]: DIABETES_HOME,
  [CEREBRAL_EDEMA_MINOR_CRITERIA]: DIABETES_HOME,
  [ROUTINE_RAPID_INSULIN_DOING]: DIABETES_HOME,
  [ROUTINE_INSULIN_PUMP_WORKING]: DIABETES_HOME,
  [ROUTINE_INSULIN_HAVE_ACCESS]: DIABETES_HOME,
  [ROUTINE_INSULIN_GLUCOSE]: DIABETES_HOME,
  [ROUTINE_INSULIN_FINISH]: DIABETES_HOME,
  [ROUTINE_INSULIN_KETONES]: DIABETES_HOME,
  [ROUTINE_INSULIN_DOSE]: DIABETES_HOME,
  [ROUTINE_INSULIN_KETONES_DOSAGE]: DIABETES_HOME,
  [ROUTINE_INSULIN_PATIENT_INFO]: DIABETES_HOME,
  [ROUTINE_INSULIN_ABOUT_TO_EAT]: DIABETES_HOME,
  [ROUTINE_INSULIN_CARB_RATIO]: DIABETES_HOME,
  [ROUTINE_INSULIN_CARB_3_HOURS]: DIABETES_HOME,
  [CEREBRAL_EDEMA_LIKELY]: DIABETES_HOME,
  [CEREBRAL_EDEMA_NOT_LIKELY]: DIABETES_HOME,
  [HYPOGLYCEMIA_MANAGEMENT_GLUCOSE]: DIABETES_HOME,
  [ROUTINE_INSULIN_NO_ACTION]: DIABETES_HOME
}