export const RESPIRATORY_SCORING = "Respiratory";
export const RETRACTIONS_SCORING = "Retractions";
export const DYSPNEA_SCORING = "Dyspnea";
export const AUSCULTATION_SCORING = "Auscultation"

export const NORMAL_FEEDING_OPTION = "A_RS_DYSPNEA_NORMAL";
export const DECREASED_APETITE_OPTION = "A_RS_DYSPNEA_DECREASEDAPP";
export const INCREASED_COUGHING_OPTION = "A_RS_DYSPNEA_COUGHING";
export const HYPERACTIVITY_OPTION = "A_RS_DYSPNEA_HYPERACTIVITY";
export const STOPS_EATING_OPTION = "A_RS_DYSPNEA_STOPEATORDRINK";
export const STOPS_PLAYING_OPTION = "A_RS_DYSPNEA_STOPPLAY";
export const DROWSY_OPTION = "A_RS_DYSPNEA_DROWSYCONFUSED";

export const NORMAL_BREATHE_OPTION = "A_RS_AUSC_NORMAL";
export const END_EXPIRATORY_OPTION = "A_RS_AUSC_ENDEXPWHEEZE";
export const EXPIRATORY_PHASE_OPTION = "A_RS_AUSC_EXPWHEEZE";
export const INSPIRATORY_WHEESE_OPTION = "A_RS_AUSC_INSPWHEEZE";
export const DIMINISHED_BREATH_OPTION = "A_RS_AUSC_DIMINISHEDSOUNDS";

export const DYSPNEA_COUNT_MORE_10_OPTION = 'A_RS_DYSPNEA_GE10'
export const DYSPNEA_COUNT_79_OPTION = 'A_RS_DYSPNEA_79'
export const DYSPNEA_COUNT_46_OPTION = 'A_RS_DYSPNEA_46'
export const DYSPNEA_COUNT_LESS_3_OPTION = 'A_RS_DYSPNEA_LE3'