export const TWENTY_NINE_SIXTY_DISCLAIMER = '22-28 Disclaimer';
export const DIAGNOSTIC_TESTS = '22-28 Diagnostic Tests';
export const BACTERIAL_INFECTION_ASSESMENT = '22 - 28 Bacterial Infection Assesment';
export const HIGH_RISK_FOR_BACTERIAL_INFECTION = '22 - 28 Increased Risk for Bacterial Infection'
export const HSV_CHECKLIST = '22 - 28 HSV Checklist';
export const HSV_HIGH_RISK_RECOMMENDATIONS = '22 - 28 HSV High Risk Recommendations';
export const ADMISSION_ANTIBIOTIC_RECOMMENDATIONS = '22 - 28 Admission Antibiotic Recommendations';
export const INPAINET_OBSERVATIONS = '22 - 28 Inpatient Observations';
export const DISCHARGE_ADMISSION_CHECKLIST = '22 - 28 Discharge Admission Checklist';
export const FURTHER_RECOMENDATIONS_OBSERVATIONS = '22 - 28 Further Recommendations Observations';
export const LOW_RISK_BACTERIAL_RECOMMENDATIONS = '22 - 28 Low Risk Bacterial Recommendations';
export const DISCHARGE_CHECKLIST_LOW_RISK = '22 - 28 Discharge Checklist Low Risk';
export const LOW_RISK_ADMISSION_RECOMMENDATIONS = '22 - 28 Low Risk Admission Recommendations';
export const OPTIONAL_ANTIBIOTICS_OPTIONS = '22 - 28 Optional Antibiotics Options';
export const OBSERVATION_TREATMENT = '22 - 28 Observation/Treatment Low Risk';
export const DISCHARGE_RECOMMENDATIONS = '22 - 28 Discharge Recommendations';
export const HSV_LOW_RISK_RECOMMENDATIONS = '22 - 28 HSV Low Risk Recommendations';
export const DISPOSITION_RECOMMENDATIONS = '22 - 28 Disposition Recommendations';
export const HIGH_RISK_HOSPITAL_ADMISSION_FIRST = '22 - 28 High Risk Hospital Admission First';
export const HIGH_RISK_HOSPITAL_ADMISSION_SECOND = '22 - 28 High Risk Hospital Admission Second';
export const HIGH_RISK_HOSPITAL_ADMISSION_THIRD = '22 - 28 High Risk Hospital Admission Third';
export const DISCHARGE_CHECKLIST = '22 - 28 Discharge Checklist';
export const DISPOSITION_RECOMMENDATIONS_LOW = '22 - 28 Disposition Recommendations Low Risk';

const TWENTY_NINE_SIXTY = '22 - 28 Days';

export const TWENTY_NINE_SIXTY_TITLE_OVERRIDES = {
  [TWENTY_NINE_SIXTY_DISCLAIMER]: TWENTY_NINE_SIXTY,
  [DIAGNOSTIC_TESTS]: TWENTY_NINE_SIXTY,
  [BACTERIAL_INFECTION_ASSESMENT]: TWENTY_NINE_SIXTY,
  [HIGH_RISK_FOR_BACTERIAL_INFECTION]: TWENTY_NINE_SIXTY,
  [HSV_CHECKLIST]: TWENTY_NINE_SIXTY,
  [HSV_HIGH_RISK_RECOMMENDATIONS]: TWENTY_NINE_SIXTY,
  [ADMISSION_ANTIBIOTIC_RECOMMENDATIONS]: TWENTY_NINE_SIXTY,
  [INPAINET_OBSERVATIONS]: TWENTY_NINE_SIXTY,
  [DISCHARGE_ADMISSION_CHECKLIST]: TWENTY_NINE_SIXTY,
  [FURTHER_RECOMENDATIONS_OBSERVATIONS]: TWENTY_NINE_SIXTY,
  [LOW_RISK_BACTERIAL_RECOMMENDATIONS]: TWENTY_NINE_SIXTY,
  [DISCHARGE_CHECKLIST_LOW_RISK]: TWENTY_NINE_SIXTY,
  [LOW_RISK_ADMISSION_RECOMMENDATIONS]: TWENTY_NINE_SIXTY,
  [OPTIONAL_ANTIBIOTICS_OPTIONS]: TWENTY_NINE_SIXTY,
  [DISCHARGE_RECOMMENDATIONS]: TWENTY_NINE_SIXTY,
  [HSV_LOW_RISK_RECOMMENDATIONS]: TWENTY_NINE_SIXTY,
  [OBSERVATION_TREATMENT]: TWENTY_NINE_SIXTY,
  [DISPOSITION_RECOMMENDATIONS]: TWENTY_NINE_SIXTY,
  [HIGH_RISK_HOSPITAL_ADMISSION_FIRST]: TWENTY_NINE_SIXTY,
  [HIGH_RISK_HOSPITAL_ADMISSION_SECOND]: TWENTY_NINE_SIXTY,
  [HIGH_RISK_HOSPITAL_ADMISSION_THIRD]: TWENTY_NINE_SIXTY,
  [DISPOSITION_RECOMMENDATIONS_LOW]: TWENTY_NINE_SIXTY,

}