export const antibioticsText = {
  home: {
    title: 'Antibiotics',
    pathways: 'Select Infection Type',
    acuteBacterial: 'Acute Bacterial Rhinosinusitis',
    acuteOtitis: 'Acute Otitis Media',
    bronchiolitis: 'Bronchiolitis',
    pneumonia: 'Community Acquired Pneumonia',
    skinInfection: 'Skin and Soft Tissue Infection',
    strepPharyngitis: 'Strep Pharyngitis',
    urinaryTractInfection: 'Urinary Tract Infection/Pyelonephritis',
    disclaimer: 'Disclaimer: ',
    disclaimerFirst: 'These guides are designed to direct ',
    disclaimerItalic: 'initial',
    disclaimerSecond: ' antibiotic therapy for immunocompetent patients and should not replace clinical judgment. Antibiotic selection should be guided by clinical response and local susceptibilities. Definitive therapy should be tailored to available culture results when available. Seek expert consultation for immunocompromised patients.'
  },
  acuteBacterial: {
    info: 'Information',
    definition:' ABRS is an infection involving the paranasal sinuses.',
    signsAndSymptoms:' : A diagnosis of ABRS should be considered if a patient with upper respiratory symptoms presents with any of the following:',
    note:'Note: ABRS is uncommon in children <2 years.',
    testing:' The diagnosis of ABRS can be made clinically. Laboratory testing is generally not recommended. Imaging is not recommended unless there are concerns for orbital or intracranial complications.​',
    commonBacteria:' Haemophilus influenzae (non-typeable), Streptococcus pneumaniae, Moraxella catarrhalis',
    symptomOne:'1)  Persistent nasal discharge, daytime cough, or both lasting >10 days without improvement.',
    symptomTwo:'2)  Worsening or new onset of nasal discharge, daytime cough, or fever after initial improvement.',
    symptomThree:'3)  Severe onset (temperature ≥39°C) and purulent nasal discharge for ≥3 days.',
    allergyAssesment: "Allergy Assessment",
    allergyQuestion: 'Does the patient have an allergy to penicillin or cephalosporin?',
    treatmentPenicillinAllergy: "Treatment Recommendations Penicillin or Cephalosporin Allergy",
    treatmentNoAllergy:"Treatment Recommendations\nNo Allergy",
    treatmentMildNoAllergy:'Mild to Moderate Disease',
    treatmentSevereNoAllergy:`Severe Disease\nOR\nMild to Moderate Disease and Age ${'\u003C'} 2 Years, Attends Daycare, or Received Antibiotics in Past 30 Days`,
    mildModeratePenicillinAllergy: "Mild to Moderate Penicillin Allergy​\n(e.g. Rashes Including Hives)​",
    severePenicillinAllergy: 'Severe Penicillin or Cephalosporin Allergy\n(e.g. Anaphylaxis)',

  },
  studyIdConfirmation:{
    title: "Enter your Study ID",
    studyId: "Study ID"
  },
  acuteOtitis: {
    info: 'Information',
    definition: ' AOM is an infection of the middle ear.',
    signsAndSymptoms: ' : A diagnosis of AOM should be considered if a patient has a middle ear effusion PLUS one of the following:​',
    testing: ' The diagnosis of AOM can be made clinically. Laboratory testing and imaging are generally not recommended.',
    commonBacteria: ' Haemophilus influenzae (nontypeable), Streptococcus pneumoniae, Moraxella catarrhalis​',
    exceptions: 'Infants <6 months of age and those with tympanostomy tubes, craniofacial abnormalities, immunodeficiency or cochlear implants are off guideline and may require additional diagnostic and management considerations that are not discussed here.',
    antibioticDecitionSupport: 'Antibiotic Decision Support',
    severityAssesment: 'Severity Assessment',
    additionalFeaturesAssesment: 'Additional Features Assesment',
    anyOfFollowingTrue: 'Are any of the following true?',
    allergyAssesment: "Allergy Assessment",
    allergyQuestion: 'Does the patient have an allergy to penicillin or cephalosporin?',
    treatmentPenicillinAllergy: "Treatment Recommendations Penicillin or Cephalosporin Allergy",
    mildModeratePenicillinAllergy: "Mild to Moderate Penicillin Allergy​\n(e.g. Rashes Including Hives)​",
    severePenicillinAllergy: 'Severe Penicillin or Cephalosporin Allergy',
    additionalFeatures: 'Additional Features Assessment',
    treatmentRecentUse: 'Treatment Recommendations Recent Antibiotic Use or Recurrence',
    treatmentNoAllergy: 'Treatment Recommendations\nNo Allergy',
    ageAssesment: 'Age Assesment',
    ageQuestion: 'What is the age of the child?',
    ageFirst: 'Age 6 months to 2 years',
    ageSecond: 'Age > 2 years',
    watchfulWaiting: 'Watchful Waiting',
    waitingInfoFirst: 'Consider watchful waiting for the following children without otorrhea and with mild symptoms (mild or no otalgia, fever <39°C, onset <48 hours, access to follow-up available):',
    waitingInfoSecond: 'Watchful waiting is a joint decision between family and medical provider. If watchful waiting is chosen, ensure close follow-up within 48 to 72 hours and need for a safety-net antibiotic prescription.',
    antibioticsAreIndicated: 'Antibiotics are Indicated',
    bilateralDesease: 'Bilateral Disease Assessment',
    deseaseQuestion: 'Does the patient have bilateral AOM?'
  },
  shared: {
    definition: 'Definition:',
    signsAndSymptoms: 'Signs and Symptoms:',
    testing: 'Testing:',
    treatment: 'Treatment:',
    commonBacteria: 'Common Bacteria:',
    guidelineExceptions: 'Guideline exceptions:',
    submit: 'Submit',
    selectTreatment: "Select a treatment option",
    home: 'Antibiotics Home',
    firstLine: 'First Line',
    noNotes: "No applicable notes",
    notes: 'Notes:',
    alternative: 'Alternatives',
    antibioticDecitionSupport: 'Antibiotic Decision Support',
    anyOfFollowingTrue: 'Are any of the following true?'
  },
  bronchiolitis: {
    info: 'Information',
    definition: ' Bronchiolitis is caused by a viral infection of the lower respiratory tract. It commonly occurs in infants and young children. Respiratory syncytial virus (RSV) is one of the most common etiologies, although numerous viruses can cause bronchiolitis.',
    signsAndSymptoms: ' Bronchiolitis is characterized by rhinitis, cough, wheezing, tachypnea, and increased work of breathing. Infants and young children with bronchiolitis may have wheezes, rhonchi, and rales on auscultation.',
    testing: ' Diagnostic testing should not be routinely obtained, and antibiotics should not be routinely administered for children with acute bronchiolitis.',
    treatment: ' Antibiotics should only be prescribed in cases where there is clinical suspicion for concomitant bacterial infection.'
  },
  skinInfection: {
    info: 'Information',
    definition: ' SSTIs include a wide range of  infections from impetigo to rapidly progressive necrotizing fasciitis. The treatment of SSTIs largely depends on the most likely causative organisms, location of infection and severity of disease.',
    signsAndSymptoms: ' A diagnosis of SSTI should be considered in a patient presenting with one or more of the following:​',
    testing: ' Laboratory testing and imaging are not routinely recommended for healthy patients with mild infection. Indications for additional testing include severe local infection, systemic signs (e.g., fever), and failure to respond to initial antibiotic therapy.​',
    commonBacteria: ' methicillin-sensitive Staphylococcus aureus (MSSA), methicillin-resistant Staphylococcus aureus (MRSA), S. pyogenes, Polymicrobial (e.g., Necrotizing Fasciitis, dirty wounds)',
    selectInfection: 'Select Infection Type',
    treatment: "Treatment Recommendations",
    severePenicillinAllergy: 'Severe Penicillin or Cephalosporin Allergy\n(e.g. Anaphylaxis)',
    mrsaSuspected: 'MRSA Suspected, Severe Penicillin or Cephalosporin Allergy\n(e.g. Anaphylaxis)',
    necrotizing: 'This is a medical emergency. Seek Surgery and Infectious Diseases consultation immediately.',
    penicillinAllergy: 'Penicillin or Cephalosporin Allergy'
  },
  pneumonia: {
    info: 'Information',
    definition: ' CAP is an infection of the airways and lung tissue. CAP is caused by a multitude of organisms, including viral and bacterial etiologies.​',
    signsAndSymptoms: ' A diagnosis of CAP should be considered in children with fever, cough, or respiratory distress (eg hypoxemia, tachypnea). Findings that may be present on examination include focal crackles, decreased breath sounds, bronchial breath sounds, pectoriloquy (increased loudness on auscultation with whispering), and tactile fremitus (vibration felt on chest with low frequency vocalization).​',
    testing: ' Routine chest radiographs and diagnostic testing are not indicated for confirmation of suspected CAP in patients who are well enough to be treated in ambulatory settings. Chest radiographs should be considered for all patients hospitalized for management of CAP to assess for complications of pneumonia including effusion and empyema.',
    commonBacteria: ' Streptococcus pneumoniae, Haemophilus influenzae (non-typeable), Viral, Atypical bacteria (e.g. Mycoplasma pneumoniae)',
    exceptions: 'Infants <3 months of age, those with immunodeficiency, chronic pleural disease, systemic illness concerning for sepsis, or hospital acquired pneumonia are off guideline and may require additional diagnostic and management considerations that are not discussed here.',
    viralAssesment: 'Viral Assessment',
    viralAssesmentInfo: "Viral pneumonia commonly presents in children <5 years of age. Onset is typically gradual with preceding upper respiratory symptoms. Wheezing with diffuse, bilateral findings (e.g. crackles) on auscultation is common. Chest radiography demonstrates interstitial infiltrates.​",
    viralAssesmentSubinfo: 'Influenza should be considered in children with concern for viral pneumonia during influenza season (winter months).',
    viralAssesmentQuestion: 'Is there concern for a viral pneumonia?',
    atypicalAssessment: 'Atypical Bacterial Assessment',
    atypicalAssessmentInfo: 'Atypical bacterial pneumonia can present in children of all ages, but typically in those > 5 years. Onset is typically abrupt with constitutional findings (e.g. malaise, myalgia, rash, conjunctivitis, headache, sore throat). Cough is typically described as gradually worsening and nonproductive. Wheezing and extrapulmonary manifestations (e.g. hemolytic anemia) may be observed. Chest X-Ray demonstrates interstitial infiltrates.​',
    atypicalAssessmentQuestion: 'Is there concern for an atypical bacterial pneumonia?',
    severityAssesment: 'Severity Assessment',
    allergyAssesment: 'Allergy Assessment',
    allergyQuestion: 'Does the patient have an allergy to penicillin or cephalosporin?',
    oralTreatment: 'Oral Treatment Recommendations​',
    treatmentPenicillin: 'Treatment Recommendations Penicillin or Cephalosporin Allergy',
    effisionAssesment: 'Effusion and Empyema Assessment',
    effusionQuestion: 'Does the patient have a moderate or large effusion or empyema?',
    moderateEffusion: 'Moderate effusion or empyema:',
    moderateEffusionInfo: ' >10 mm rim of fluid but opacifies less than half of the hemithorax.',
    largeEffusion: 'Large effusion or empyema:',
    largeEffusionInfo: ' opacifies more than half of the hemithorax.',
    treatmentEffusion: 'Treatment Recommendations Effusion or Empyema',
    treatmentEffusionInfo: 'If a clinically significant (i.e., moderate or large) parapneumonic effusion or empyema is found consider expert consultation for additional diagnostic and management considerations including discussion of chest tube placement and fibrinolysis.',
    antibioticReccomendations: 'Antibiotic Recommendations',
    ivTreatment: 'IV Treatment Recommendations​',
    severePenicillinAllergy: 'Severe Penicillin or Cephalosporin Allergy\n(e.g. Anaphylaxis)',
    atypicalBacteriaTreatment: 'Atypical Bacteria Treatment Recommendations',
    viralTreatment: 'Viral Treatment Recommendations',
    viralTreatmentInfo: 'Consider testing for influenza during influenza season. Routine testing for other viruses should be avoided if clinical suspicion for bacterial co-infection is high and antibacterial therapy is indicated.​',
    viralTreatmentSubinfo: 'If influenza positive and moderate to severe respiratory symptoms are present, consider starting influenza antiviral therapy as soon as possible. Antibiotics are not necessary in children with positive influenza testing in the absence of clinical data suggesting bacterial co-infection.​',
    viralTreatmentTitle: 'Treatment for Influenza',
    viralTreatmentSubtitle: 'Oseltamivir (Tamiflu)',
    coInfection: 'Concern for Bacterial Co-infection'
  },
  pharyngitis: {
    info: 'Information',
    definition: ' GAS is a bacterial infection of the throat.​',
    signsAndSymptoms: ' A diagnosis of GAS pharyngitis should be considered in patients presenting with acute sore throat and fever with exam findings demonstrating one or more of the following:',
    signsAndSymptomsSecond: ' Patients with concomitant cough, rhinorrhea/nasal congestion, conjunctivitis, hoarseness, mouth ulcers, diarrhea, or viral exanthems are unlikely to have GAS pharyngitis and testing should be avoided.​',
    testing: ' Testing with throat culture or rapid antigen detection tests are recommended. Testing children <3 years of age is generally not indicated unless they present with signs and symptoms of GAS pharyngitis and have a household contact with a positive streptococcal rapid antigen test or culture.​',
    commonBacteria: ' Group A streptococcus (Streptococcus pyogenes)​',
    allergyAssesment: 'Allergy Assessment',
    allergyQuestion: 'Does the patient have an allergy to penicillin or cephalosporin?',
    noAllergy: 'Treatment Recommendations\nNo Allergy',
    treatmentAllergy: 'Treatment Recommendations Penicillin or Cephalosporin Allergy',
    severePenicillinAllergy: 'Severe Penicillin or Cephalosporin Allergy\n(e.g. Anaphylaxis)'
  },
  urinaryTract: {
    home: 'Information',
    definition: ' A UTI is an infection involving the urinary tract. An infection involving the upper urinary tract or kidney is referred to as pyelonephritis',
    signsAndSymptoms: ' A diagnosis of UTI/pyelonephritis should be considered in older children with symptoms of frequency, urgency, or dysuria. A diagnosis of UTI/pyelonephritis should be considered in a febrile child without urinary symptoms if urinalysis demonstrates any combination of leukocyte esterase, nitrites, white blood cells, or bacteria.',
    testing: ' All children with concern for a UTI/pyelonephritis should have urine obtained for culture. Pure growth of ≥50,000 CFUs/mL (catheterized specimen) or ≥100,000 CFUs/mL (bag specimen) of a uropathogen and urinalysis demonstrating bacteriuria or pyuria indicate true infection.',
    commonBacteria: ' Enteric Gram-Negative Bacilli, ',
    commonBacteriaItalic: 'Enterococcus, S. saprophyticus, S. aureus',
    stewardshipNotes: 'Stewardship notes:',
    severityAssesment: 'Severity Assessment',
    treatmentUncomplicated: 'Treatment Recommendations\nUncomplicated',
    severePenicillinAllergy: 'Severe Penicillin or Cephalosporin Allergy\n(e.g. Anaphylaxis)',
    oralTolerance: 'Oral Tolerance Assessment',
    oralToleranceQuestion: 'Is the patient dehydrated or unable to tolerate oral medications?',
    ivTreatment: 'IV Treatment Recommendations',
    oralTreatment: 'Oral Treatment Recommendations'
  }
}