export const TRACHESTOMY_HOME = "T_HOME_SCREEN";
export const TRACHESTOMY_BEGIN_EMERGENCY_ALGORITHM = 'TRACHESTOMY_BEGIN_EMERGENCY_ALGORITHM';
export const TRACHESTOMY_INSERT_SAME_TUBE = 'TRACHESTOMY_INSERT_SAME_TUBE';
export const TRACHESTOMY_ATTEMPT_PASS_CATHETER = 'TRACHESTOMY_ATTEMPT_PASS_CATHETER';
export const TRACHESTOMY_TUBE_CHANGE = 'TRACHESTOMY_TUBE_CHANGE';
export const TRACHESTOMY_INSERT_SMALLER_TUBE = 'TRACHESTOMY_INSERT_SMALLER_TUBE';
export const TRACHESTOMY_CHILD_WITH_NO_TRACH = 'TRACHESTOMY_CHILD_WITH_NO_TRACH';
export const TRACHESTOMY_CHILD_WITH_RESPIRATORY_DISTRESS = 'TRACHESTOMY_CHILD_WITH_RESPIRATORY_DISTRESS';
export const TRACHESTOMY_THANK_YOU = 'TRACHESTOMY_THANK_YOU';
export const TRACHESTOMY_RESCUE_BREATHING = 'TRACHESTOMY_RESCUE_BREATHING';
export const TRACHESTOMY_NON_RESOPNSIVE_CHILD_WITH_TRACH = 'TRACHESTOMY_NON_RESOPNSIVE_CHILD_WITH_TRACH';
export const TRACHESTOMY_NON_RESOPNSIVE_CHILD_NO_TRACH = 'TRACHESTOMY_NON_RESOPNSIVE_CHILD_NO_TRACH';
export const TRACHESTOMY_CPR_WITH_TRACH_IN_PLACE = 'TRACHESTOMY_CPR_WITH_TRACH_IN_PLACE';
export const TRACHESTOMY_RESCUE_BREATHING_WITH_AIRWAY_OBFUSCATION = 'TRACHESTOMY_RESCUE_BREATHING_WITH_AIRWAY_OBFUSCATION';
export const TRACHESTOMY_RESCUE_BREATHING_NO_AIRWAY_OBFUSCATION = 'TRACHESTOMY_RESCUE_BREATHING_NO_AIRWAY_OBFUSCATION';
export const TRACHESTOMY_CPR_WITH_UPPER_AIRWAY_OBFUSCATION = 'TRACHESTOMY_CPR_WITH_UPPER_AIRWAY_OBFUSCATION';
export const TRACHESTOMY_CPR_WITH_NO_UPPER_AIRWAY_OBFUSCATION = 'TRACHESTOMY_CPR_WITH_NO_UPPER_AIRWAY_OBFUSCATION';
export const TRACHESTOMY_NON_RESOPNSIVE_CHILD_WITH_AIRWAY_OBFUSCATION = 'TRACHESTOMY_NON_RESOPNSIVE_CHILD_WITH_AIRWAY_OBFUSCATION';
export const TRACHESTOMY_NON_RESOPNSIVE_CHILD_NO_AIRWAY_OBFUSCATION = 'TRACHESTOMY_NON_RESOPNSIVE_CHILD_NO_AIRWAY_OBFUSCATION';

export const TRACHESTOMY_HOME_TITLE = `Tracheostomy Emergency ${"\n"}Airway Management`;

export const TRACH_TITLE_OVERRIDES = {
  [TRACHESTOMY_HOME]: TRACHESTOMY_HOME_TITLE,
  [TRACHESTOMY_BEGIN_EMERGENCY_ALGORITHM]: TRACHESTOMY_HOME_TITLE,
  [TRACHESTOMY_INSERT_SAME_TUBE]: TRACHESTOMY_HOME_TITLE,
  [TRACHESTOMY_ATTEMPT_PASS_CATHETER]: TRACHESTOMY_HOME_TITLE,
  [TRACHESTOMY_TUBE_CHANGE]: TRACHESTOMY_HOME_TITLE,
  [TRACHESTOMY_INSERT_SMALLER_TUBE]: TRACHESTOMY_HOME_TITLE,
  [TRACHESTOMY_CHILD_WITH_NO_TRACH]: TRACHESTOMY_HOME_TITLE,
  [TRACHESTOMY_CHILD_WITH_RESPIRATORY_DISTRESS]: TRACHESTOMY_HOME_TITLE,
  [TRACHESTOMY_THANK_YOU]: TRACHESTOMY_HOME_TITLE,
  [TRACHESTOMY_RESCUE_BREATHING]: TRACHESTOMY_HOME_TITLE,
  [TRACHESTOMY_NON_RESOPNSIVE_CHILD_WITH_TRACH]: TRACHESTOMY_HOME_TITLE,
  [TRACHESTOMY_NON_RESOPNSIVE_CHILD_NO_TRACH]: TRACHESTOMY_HOME_TITLE,
  [TRACHESTOMY_CPR_WITH_TRACH_IN_PLACE]: TRACHESTOMY_HOME_TITLE,
  [TRACHESTOMY_RESCUE_BREATHING_WITH_AIRWAY_OBFUSCATION]: TRACHESTOMY_HOME_TITLE,
  [TRACHESTOMY_RESCUE_BREATHING_NO_AIRWAY_OBFUSCATION]: TRACHESTOMY_HOME_TITLE,
  [TRACHESTOMY_CPR_WITH_UPPER_AIRWAY_OBFUSCATION]: TRACHESTOMY_HOME_TITLE,
  [TRACHESTOMY_CPR_WITH_NO_UPPER_AIRWAY_OBFUSCATION]: TRACHESTOMY_HOME_TITLE,
  [TRACHESTOMY_NON_RESOPNSIVE_CHILD_WITH_AIRWAY_OBFUSCATION]: TRACHESTOMY_HOME_TITLE,
  [TRACHESTOMY_NON_RESOPNSIVE_CHILD_NO_AIRWAY_OBFUSCATION]: TRACHESTOMY_HOME_TITLE
}