export const resusText = {
  home: {
    title: "Resuscitation",
    tellUs: 'Tell us something about the patient:',
    newlyBornButton: "The patient is a newly born infant",
    weightButton: "Patient's weight",
    ageButton: "Patient's age",
    colorButton: "Length based tape color",
    note: "Don’t know the weight? Pick one of the following:"
  },
  patientDetails: {
    info: 'Drug calculations are age/weight based. By confirming estimated values, you acknowledge entered information and the risks therein.',
    youHaveEntered: 'You have entered:',
    weight: 'Weight',
    change: 'Change',
    age: 'Age',
    color: 'Length based tape color',
    weEstimated: "We have estimated:",
    wasPatientBornPremature: 'Was the patient born premature?',
    btnNo: 'No',
    yesGestAge2228: 'Yes - gestational age is 22 - 28 weeks',
    yesGestAge2936: 'Yes - gestational age is 29 - 36 weeks'
  },
  shared: {
    weight: 'Gestational Weight',
    age: 'Gestational Age',
    kg: 'kg',
    lbs: 'lbs',
    weeks: 'weeks',
    airway: 'Airway and Breathing',
    comp: 'Compressions',
    drugDosing: 'Drug Dosing',
    patientWeight: 'Patient Weight',
    weightPlaceholder: "Weight (kg)",
    continue: 'Continue',
    restart: 'Start Over',
    pivSizes: 'PIV Sizes',
    electricalTherapy: 'Electrical Therapy',
    tracheostomy: 'Tracheostomy',
    rapidIntubation: "Rapid Sequence Intubation",
    medications: "Medications",
    circulation: 'Circulation'
  },
  newlyBorn: {
    details: 'Patient Details',
    reset: 'Reset All',
    hint: "Don't know the weight?",
    title: 'Newly Born Infant'
  },
  drugDosing: {
    drugDosing: 'Drug Dosing',
    concentration: 'Concentration',
    dose: 'Dose -',
    initial: 'Initial',
    repeat: 'Repeat',
    initialDose: 'Initial Dose',
    administer: "Administer",
    patientVolume: 'Patient Volume -',
    patientDose: 'Patient Dose -',
    doNotExceed: 'Do NOT exceed ',
    per: ' per ',
    total: " TOTAL ",
    warnings: 'Warnings',
    contradictions: "Contraindications",
    specialPrecautions: 'Special Precautions',
    ISMPHighAlert: 'ISMP High Alert',
    additionalAdverseReactions: 'Additional Adverse Reactions',
    blackBox: 'Black Box Warnings',
    black: 'Black Box',
    lowDose: 'Low Dose',
    medDose: 'Moderate Dose',
    highDose: 'High Dose',
    doseRange: 'Dose Range',
    medicationsAndFluids: 'Medications and Fluids',
    fluidResus: 'Fluid Resuscitation',
    disclaimer: 'Preservative-free products are preferred in this population',
    repeatDose: "Repeat Dose"
  },
  resusPathways: {
    newlyBornInfant: 'Newly Born Infant',
    basicLifeSupport: 'Basic Life Support',
    advancedLifeSupport: 'Advanced Life Support',
    burnManagment: 'Burn Management',
    vitalSigns: 'Vital Signs & Assessments',
    drugDosing: 'Drug Dosing',
    equipemntSizes: 'Equipment Sizes'
  },
  circulaton: {
    codeDrugs: 'Code Drugs',
    fluidResus: "Fluid Resuscitation",
    cardioDrips: 'Cardiovascular Drips',
    maintanenceFluids: 'Maintenance Fluids',
    bolus20: 'Bolus NS or LR (20 mL/kg)',
    bolus10: 'Bolus NS or LR (10 mL/kg)',
    selectDrug: 'Select Drug',
    selectDose: 'Select Dose',
    selectConcentration: 'Select Concentration',
    mlhr: 'mL/hr',
  },
  electricalTherapy: {
    title: 'Electrical Therapy',
    indications: 'Indications for Defibrillation',
    indicationsInfo: 'Ventricular fibrillation and pulseless ventricular tachycardia.  Perform high quality CPR while preparing to immediately defibrillate.',
    defibrillation: 'Defibrillation Dosage',
    child: "Infant/Child",
    adult: 'Adult',
    warning: 'If unfamiliar with device-specific dose, use default dose of 200 J',
    synchronizedCardio: 'Synchronized Cardioversion'
  },
  burnManagment: {
    title: 'Burn Management',
    burnsAirwayTitle: 'Airway: ',
    burnsAirwayInfo: 'Assess and establish a safe airway with 100% oxygen for anyone with suspected inhalation injury.',
    burnsFluidsTitle: 'Initial Fluids: ',
    burnsFluidsInfo: 'For burns clearly exceeding 20% TBSA not including superficial (1st degree) burns, start initial IV fluid resuscitation.',
    burnsManagementTitle: 'Management: ',
    burnsManagementInfo: 'Ensure burn sites are warm, dry, and covered once TBSA is calculated.',
    burns4thInfo: 'Assess and establish a safe airway with 100% oxygen for anyone with suspected inhalation injury',
    lr: 'LR at 1.5 x maintenance',
    resultsWarning1: 'Total Body Surface Area (TBSA)',
    resultsWarning2: 'Burned Calculation',
    calcTitle: 'Calculate TBSA',
    calculatorTitle: 'Total Burned Body Surface Area Calculation:',
    adjustedFluidRates: 'Adjusted Fluid Rate for Burns >20%',
    calcInfo: 'Calculate total burned body surface area for all 2nd and 3rd degree burns',
    less20BurnTitle: 'Burns <20% TBSA not including superficial (1st degree) burns',
    youHaveDetermined: "You have determined that the patient's burn is less than 20% TBSA",
    treatmentLess20Info: 'Please call nearest burn center for transfer and clinical recommendations and transfer if any one of the following criteria are met:',
    burnSize: 'Burn Size',
    burnInjury: 'Burns with the following injury mechanism:',
    injuryLocations: 'Injury including any of these anatomical locations:',
    additionalConsiderations: 'Additional considerations for consultation with burn center:',
    back: "Back",
    restart: 'Restart',
    treatmentRecommendations: 'Treatment recommendations',
    preTreatment: "Pre-treatment questions",
    wasTheBurnCausedBy: 'Was the burn caused by an electrical injury?',
    howManyHours: 'How many hours since the burn?',
    totalFluidVolume: 'Total IV fluid volume infused (including boluses) since injury',
    nextSteps: "Next Steps",
    burnResus: 'Burn Resuscitation hourly rate for remaining 1-8 hours since injury',
    burnResusMoreHours: 'Burn Resuscitation hourly rate for remaining 9-24 hours since injury',
    lrAst: 'LR*',
    next: "Next",
    plusD5: 'Plus D₅LR maintenance fluids hourly rate',
    d5subInfo: '*if LR is not available, saline is an appropriate substitute',
    moreHours: 'View Hours 9-24',
    volume24Recommended: 'Total 24-hour volume recommended:',
    total24hoursVolume: ' = 24 hour total fluid volume',
    showEquation: 'View Equation Reference',
    euqationReference: 'Equation Reference',
    warning: 'Please call nearest burn center for transfer and clinical recommendations'
  },
  vitalSigns: {
    title: 'Vital Signs & Assessments',
    expectedVitals: 'Expected Vitals',
    heartRate: 'Heart Rate',
    avpu: 'AVPU'
  }
}