export const ANTIBIOTICS_HOME = 'Antibiotics'
export const ACUTE_BACTERIAL_RHINOSINUSITIS='Acute Bacterial Rhinosinusitis (ABRS)'
export const ACUTE_BACTERIAL_ALLERGY_ASSESMENT='Acute Bacterial Allergy Assesmen'
export const ACUTE_BACTERIAL_TREATMENT_NO_ALLERGY = 'Acute Bacterial Treatment No Allergy';
export const ACUTE_BACTERIAL_TREATMENT_ALLERGY = 'Acute Bacterial Treatment Allergy';
export const ACUTE_BACTERIAL_DRUG_DISPLAY = 'Acute Bacterial Drug Display';

export const STUDY_ID_CONFIRMATION = 'Study Id Confrimation';
export const ACUTE_OTITIS_HOME = 'Acute Otitis Media (AOM)';
export const ACUTE_OTITIS_SEVERITY_ASSESMENTS = 'Acute Otitis Severity Assessments';
export const ACUTE_OTITIS_ALLERGY_ASSESMENT = 'Acute Otitis Allergy Assesment';
export const ACUTE_OTITIS_TREATMENT_PENICILLIN = 'Acute Otitis Treatment Penicillin';
export const ACUTE_OTITIS_DRUG_DISPLAY = 'Acute Otitis Drug Display';
export const ACUTE_OTITIS_ADDITIONAL_FEATURES = 'Acute Otitis Additional Features';
export const ACUTE_OTITIS_TREATMENT_RECENT_USE = 'Acute Otitis Treatment Recent Use';
export const ACUTE_OTITIS_TREATMENT_NO_ALLERGY = 'Acute Otitis Treatment No Allergy';
export const ACUTE_OTITIS_AGE_ASSESMENT = 'Acute Otitis Age Assesment';
export const ACUTE_OTITIS_WATCHFUL_WAITING = 'Acute Otitis Watchful Waiting';
export const ACUTE_OTITIS_BILATERAL_DESEASE = 'Acute Otitis Bilateral Desease';
export const BRONCHIOLITIS = 'Bronchiolitis';
export const SKIN_INFECTION_HOME = 'Skin and Soft Tissue Infection (SSTI)';
export const SKIN_INFECTION_SELECT = 'Skin Infection Select';
export const SKIN_INFECTION_DRUG_DISPLAY = 'Skin Infection Drug Display';
export const SKIN_INFECTION_IMPETIGO = 'Skin Infection Impetigo Treatment';
export const SKIN_INFECTION_CELLULITIS = 'Skin Infection Cellulitis';
export const SKIN_INFECTION_ABSCESS = 'Skin Infection Abscess';
export const SKIN_INFECTION_NECROTIZING = 'Skin Infection Necrotizing';
export const SKIN_INFECTION_BITE = 'Skin Infection Bite';
export const PNEUMONIA_HOME = 'Community Acquired Pneumonia (CAP)';
export const PNEUMONIA_VIRAL_ASSESMENT = 'Pneumonia Viral Assessment';
export const PNEUMONIA_ATYPICAL_ASSESMENT = 'Pneumonia Atypical Assessment';
export const PNEUMONIA_SEVERITY_ASSESMENT = 'Pneumonia Severity Assessment';
export const PNEUMONIA_ALLERGY_ASSESMENT = 'Pneumonia Allergy Assessment';
export const PNEUMONIA_ORAL_TREATMENT = 'Pneumonia Oral Treatment';
export const PNEUMONIA_DRUG_DISPLAY = 'Pneumonia Drug Display';
export const PNEUMONIA_TREATMENT_PENICILLIN = 'Pneumonia Treatment Penicillin';
export const PNEUMONIA_EFFUSION_ASSESMENT = 'Pneumonia Effusion Assesment';
export const PNEUMONIA_TREATMENT_EFFUSION = 'Pneumonia Treatment Effusion';
export const PNEUMONIA_IV_TREATMENT = 'Pneumonia IV Treatment';
export const PNEUMONIA_ATYPICAL_BACTERIA_TREATMENT = 'Pneumonia Atypical Bacteria Treatment';
export const PNEUMONIA_VIRAL_TREATMENT = 'Pneumonia Viral Treatment';
export const PHARYNGITIS_HOME = 'Group A Strep (GAS) Pharyngitis';
export const PHARYNGITIS_ALLERGY_ASSESMENT = 'Pharyngitis Allergy Assesment';
export const PHARYNGITIS_DRUG_DISPLAY = 'Pharyngitis Drug Display';
export const PHARYNGITIS_NO_ALLERGY = 'Pharyngitis No Allergy';
export const PHARYNGITIS_TREATMENT_ALLERGY = 'Pharyngitis Treatment Allergy';
export const URINARY_TRACT_HOME = 'Urinary Tract Infection & Pyelonephritis';
export const URINARY_TRACT_SEVERITY_ASSESSMENT = 'Urinary Tract Severity Assessment';
export const URINARY_TRACT_DRUG_INFO = 'Urinary Tract Drug Info';
export const URINARY_TRACT_TREATMENT_UNCOMPLICATED = 'Urinary Tract Treatment Uncomplicated';
export const URINARY_TRACT_ORAL_ASSESSMENT = 'Urinary Tract Oral Assessment';
export const URINARY_TRACT_IV_TREATMENT = 'Urinary Tract IV Treatment';
export const URINARY_TRACT_ORAL_TREATMENT = 'Urinary Tract Oral Treatment';

export const ABRS_TITLE_OVERRIDES = {
  [ACUTE_BACTERIAL_ALLERGY_ASSESMENT]: ACUTE_BACTERIAL_RHINOSINUSITIS,
  [ACUTE_BACTERIAL_TREATMENT_NO_ALLERGY]: ACUTE_BACTERIAL_RHINOSINUSITIS,
  [ACUTE_BACTERIAL_TREATMENT_ALLERGY]: ACUTE_BACTERIAL_RHINOSINUSITIS,
  [ACUTE_BACTERIAL_DRUG_DISPLAY]: ACUTE_BACTERIAL_RHINOSINUSITIS
}

export const AOM_TITLE_OVERRIDES = {
  [ACUTE_OTITIS_SEVERITY_ASSESMENTS]: ACUTE_OTITIS_HOME,
  [ACUTE_OTITIS_ALLERGY_ASSESMENT]: ACUTE_OTITIS_HOME,
  [ACUTE_OTITIS_TREATMENT_PENICILLIN]: ACUTE_OTITIS_HOME,
  [ACUTE_OTITIS_DRUG_DISPLAY]: ACUTE_OTITIS_HOME,
  [ACUTE_OTITIS_ADDITIONAL_FEATURES]: ACUTE_OTITIS_HOME,
  [ACUTE_OTITIS_TREATMENT_RECENT_USE]: ACUTE_OTITIS_HOME,
  [ACUTE_OTITIS_TREATMENT_NO_ALLERGY]: ACUTE_OTITIS_HOME,
  [ACUTE_OTITIS_AGE_ASSESMENT]: ACUTE_OTITIS_HOME,
  [ACUTE_OTITIS_WATCHFUL_WAITING]: ACUTE_OTITIS_HOME,
  [ACUTE_OTITIS_BILATERAL_DESEASE]: ACUTE_OTITIS_HOME
}

export const SSTI_TITLE_OVERRIDES = {
  [SKIN_INFECTION_SELECT]: SKIN_INFECTION_HOME,
  [SKIN_INFECTION_DRUG_DISPLAY]: SKIN_INFECTION_HOME,
  [SKIN_INFECTION_IMPETIGO]: SKIN_INFECTION_HOME,
  [SKIN_INFECTION_CELLULITIS]: SKIN_INFECTION_HOME,
  [SKIN_INFECTION_ABSCESS]: SKIN_INFECTION_HOME,
  [SKIN_INFECTION_NECROTIZING]: SKIN_INFECTION_HOME,
  [SKIN_INFECTION_BITE]: SKIN_INFECTION_HOME,
}

export const CAP_TITLE_OVERRIDES = {
  [PNEUMONIA_VIRAL_ASSESMENT]: PNEUMONIA_HOME,
  [PNEUMONIA_ATYPICAL_ASSESMENT]: PNEUMONIA_HOME,
  [PNEUMONIA_SEVERITY_ASSESMENT]: PNEUMONIA_HOME,
  [PNEUMONIA_ALLERGY_ASSESMENT]: PNEUMONIA_HOME,
  [PNEUMONIA_ORAL_TREATMENT]: PNEUMONIA_HOME,
  [PNEUMONIA_DRUG_DISPLAY]: PNEUMONIA_HOME,
  [PNEUMONIA_TREATMENT_PENICILLIN]: PNEUMONIA_HOME,
  [PNEUMONIA_EFFUSION_ASSESMENT]: PNEUMONIA_HOME,
  [PNEUMONIA_TREATMENT_EFFUSION]: PNEUMONIA_HOME,
  [PNEUMONIA_IV_TREATMENT]: PNEUMONIA_HOME,
  [PNEUMONIA_ATYPICAL_BACTERIA_TREATMENT]: PNEUMONIA_HOME,
  [PNEUMONIA_VIRAL_TREATMENT]: PNEUMONIA_HOME,
}

export const GAS_TITLE_OVERRIDES = {
  [PHARYNGITIS_ALLERGY_ASSESMENT]: PHARYNGITIS_HOME,
  [PHARYNGITIS_DRUG_DISPLAY]: PHARYNGITIS_HOME,
  [PHARYNGITIS_NO_ALLERGY]: PHARYNGITIS_HOME,
  [PHARYNGITIS_TREATMENT_ALLERGY]: PHARYNGITIS_HOME,
}

export const UTI_TITLE_OVERRIDES = {
  [URINARY_TRACT_SEVERITY_ASSESSMENT]: URINARY_TRACT_HOME,
  [URINARY_TRACT_DRUG_INFO]: URINARY_TRACT_HOME,
  [URINARY_TRACT_TREATMENT_UNCOMPLICATED]: URINARY_TRACT_HOME,
  [URINARY_TRACT_ORAL_ASSESSMENT]: URINARY_TRACT_HOME,
  [URINARY_TRACT_IV_TREATMENT]: URINARY_TRACT_HOME,
  [URINARY_TRACT_ORAL_TREATMENT]: URINARY_TRACT_HOME,
}

export const ANTIBIOTCN_PATHWAY_TITLE = 'Antibiotics Decision Support';