import { ABRS_TITLE_OVERRIDES, AOM_TITLE_OVERRIDES, CAP_TITLE_OVERRIDES, GAS_TITLE_OVERRIDES, SSTI_TITLE_OVERRIDES, UTI_TITLE_OVERRIDES } from "Modules/Antibiotics/navigation/routes";
import { ASTHMA_HOME, ASTHMA_HOME_TITLE, ED_AGE_SELECT, ED_ESI_CALCULATOR, ED_ESI_SELECT, ED_PATHWAY, ED_PATHWAY_TITLE, ED_TREATMENTS, INPATIENT_AGE_SELECT, INPATIENT_CALCULATOR, INPATIENT_PATHWAY, INPATIENT_PATHWAY_TITLE, INPATIENT_TREATMENTS, SMOKING_SCREENING, SMOKING_SCREENING_TITLE } from "Modules/Asthma/navigation/routes";
import { BRUE_TITLE_MAPPING } from "Modules/Brue/navigation/routes";
import { DIABETES_TITLE_MAPPING } from "Modules/Diabetes/navigation/routes";
import { ANTIBIOTIC_OPTIONS, INFANT_APPEARS_DISCLAIMERS, INFANT_APPEARS_ILL, INFANT_APPEARS_TESTS, ZERO_SIX_ANTIBIOTICS, ZERO_SIX_DAYS, ZERO_SIX_DIAGNOSTIC_TEST, ZERO_SIX_DISCLAIMER } from "Modules/FebrileInfant/navigation/routes";
import { SEVEN_TWENTY_EIGHT_TITLE_OVERRIDES } from "Modules/FebrileInfant/screens/SevenTwentyEight/routes";
import { SIXTY_NINE_NINETY_TITLE_OVERRIDES } from "Modules/FebrileInfant/screens/SixtyOneNinety/routes";
import { TWENTY_NINE_SIXTY_TITLE_OVERRIDES } from "Modules/FebrileInfant/screens/TwentyNineSixtyPathway/routes";
import { NEWLY_BORN_INFANT_HOME, NEWLY_BORN_INFANT_INPUTS, RESUS_HOME, RESUS_PATHWAYS } from "Modules/Resuscitation/navigation/routes";
import { TRACH_TITLE_OVERRIDES } from "Modules/Trachestomy/navigation/routes";

export const titleOverrides: {[key: string]: string} = {
  [ASTHMA_HOME]: ASTHMA_HOME_TITLE,
  [ED_PATHWAY]: ED_PATHWAY_TITLE,
  [ED_AGE_SELECT]: ED_PATHWAY_TITLE,
  [ED_ESI_CALCULATOR]: ED_PATHWAY_TITLE,
  [ED_ESI_SELECT]: ED_PATHWAY_TITLE,
  [ED_TREATMENTS]: ED_PATHWAY_TITLE,
  [INPATIENT_PATHWAY]: INPATIENT_PATHWAY_TITLE,
  [INPATIENT_AGE_SELECT]: INPATIENT_PATHWAY_TITLE,
  [INPATIENT_CALCULATOR]: INPATIENT_PATHWAY_TITLE,
  [INPATIENT_TREATMENTS]: INPATIENT_PATHWAY_TITLE,
  [SMOKING_SCREENING]: SMOKING_SCREENING_TITLE,
  [NEWLY_BORN_INFANT_INPUTS]: NEWLY_BORN_INFANT_HOME,
  [RESUS_PATHWAYS]: RESUS_HOME,
  [INFANT_APPEARS_DISCLAIMERS]: INFANT_APPEARS_ILL,
  [INFANT_APPEARS_TESTS]: INFANT_APPEARS_ILL,
  [ANTIBIOTIC_OPTIONS]: INFANT_APPEARS_ILL,
  [ZERO_SIX_DISCLAIMER]: ZERO_SIX_DAYS,
  [ZERO_SIX_DIAGNOSTIC_TEST]: ZERO_SIX_DAYS,
  [ZERO_SIX_ANTIBIOTICS]: ZERO_SIX_DAYS,
  ...SEVEN_TWENTY_EIGHT_TITLE_OVERRIDES,
  ...TWENTY_NINE_SIXTY_TITLE_OVERRIDES,
  ...SIXTY_NINE_NINETY_TITLE_OVERRIDES,
  ...BRUE_TITLE_MAPPING,
  ...DIABETES_TITLE_MAPPING,
  ...ABRS_TITLE_OVERRIDES,
  ...AOM_TITLE_OVERRIDES,
  ...SSTI_TITLE_OVERRIDES,
  ...CAP_TITLE_OVERRIDES,
  ...GAS_TITLE_OVERRIDES,
  ...UTI_TITLE_OVERRIDES,
  ...TRACH_TITLE_OVERRIDES
}