export const SEVEN_TWENTY_EIGHT_DISCLAIMER = '8 - 21 Disclaimer';
export const SEVEN_TWENTY_EIGHT_DIAGNOSTIC_TESTS = '8 - 21 Tests';
export const BACTERIAL_INFECTION_ASSESMENT = '8 - 21 Bacterial Infection Assesment';
export const HIGN_RISK_RECCOMENDATIONS = '8 - 21 Hign Risk Reccomendations';
export const HSV_CHECKLIST = '8 - 21 HSV Checklist';
export const HSV_EVALUATION = '8 - 21 HSV Evaluation';
export const ANTIBIOTIC_ANTIVIRAL_RECCOMENDATIONS = '8 - 21 Antibiotic/Antiviral Reccomendations';
export const ADMISSION_RECOMMENDATIONS = '8 - 21 Admission Recommendations';
export const LOW_RISK_RECOMMENDATIONS = '8 - 21 Low Risk Recommendations';
export const LOW_ANTIBIOTIC_RECOMMENDATIONS = '8 - 21 Antibiotic Recommendations';
export const HSV_RECOMMENDATIONS = '8 - 21 HSV Recommendations';
export const ANTIBIOTIC_OPTIONS = '8 - 21 Antibiotic Options';
export const URINALYSIS_QUESTIONS = 'Urinalysis Questions';
export const DIAGNOSTIC_TESTS_HIGH_RISK = '8 - 21 High Risk Diagnostic Test';
export const URINALYSIS_QUESTIONS_HIGH_RISK = 'Urinalysis Questions HIGH RISK';
export const ADMISSION_RECOMMENDATIONS_HIGH_RISK = 'Admission Recommendations High Risk';

const SEVEN_TWENTY_EIGHT_DAYS = '8 - 21 Days'

export const SEVEN_TWENTY_EIGHT_TITLE_OVERRIDES = {
  [SEVEN_TWENTY_EIGHT_DISCLAIMER]: SEVEN_TWENTY_EIGHT_DAYS,
  [SEVEN_TWENTY_EIGHT_DIAGNOSTIC_TESTS]: SEVEN_TWENTY_EIGHT_DAYS,
  [BACTERIAL_INFECTION_ASSESMENT]: SEVEN_TWENTY_EIGHT_DAYS,
  [HIGN_RISK_RECCOMENDATIONS]: SEVEN_TWENTY_EIGHT_DAYS,
  [HSV_CHECKLIST]: SEVEN_TWENTY_EIGHT_DAYS,
  [HSV_EVALUATION]: SEVEN_TWENTY_EIGHT_DAYS,
  [ANTIBIOTIC_ANTIVIRAL_RECCOMENDATIONS]: SEVEN_TWENTY_EIGHT_DAYS,
  [ADMISSION_RECOMMENDATIONS]: SEVEN_TWENTY_EIGHT_DAYS,
  [LOW_RISK_RECOMMENDATIONS]: SEVEN_TWENTY_EIGHT_DAYS,
  [LOW_ANTIBIOTIC_RECOMMENDATIONS]: SEVEN_TWENTY_EIGHT_DAYS,
  [HSV_RECOMMENDATIONS]: SEVEN_TWENTY_EIGHT_DAYS,
  [ANTIBIOTIC_OPTIONS]: SEVEN_TWENTY_EIGHT_DAYS
}