export const SIXTY_ONE_NINETY_DISCLAIMER = '61 - 90 Disclaimer';
export const RECOMMENDED_EVALUATION = '61 - 90 RECOMMENDED EVALUATION';
export const DIAGNOSTIC_TEST = "61-90_DIAGNOSTIC_TEST";
export const HSV_CHECKLIST = "HSV_CHECKLIST";
export const HIGH_RISK_HSV = "HIGH_RISK_HSV";
export const HOSPITAL_ADMISSION = "HOSPITAL_ADMISSION";
export const LOW_HSV_RISK = "LOW_HSV_RISK";
export const HIGH_RISK_BACKTERIAL_INFECTION = "HIGH_RISK_BACKTERIAL_INFECTION";
export const HIGH_RISK_BACTERIAL_DISPOSITION = "HIGH_RISK_BACTERIAL_DISPOSITION"
export const HOSPITAL_ADMISSION_RECOMMENDATION = "HOSPITAL_ADMISSION_RECOMMENDATION";
export const DISPOSITION_RECCOMENDATION = "DISPOSITION_RECCOMENDATION";
export const DISPOSITION_RECCOMENDATION_1A = "DISPOSITION_RECCOMENDATION_1A";
export const DISCHARGE_CHECKLIST = "DISCHARGE_CHECKLIST";
export const HIGH_RISK_RECOMMENDATION = "HIGH_RISK_RECOMMENDATION";
export const HOSPITAL_ADMISSION_1B = "HOSPITAL_ADMISSION_1B"; 
export const HOSPITAL_ADMISSION_1D = "HOSPITAL_ADMISSION_1D"; 
export const DISCHARGE_CHECKLIST_LOW_RISK = "DISCHARGE_CHECKLIST_LOW_RISK";
export const HOSPITAL_ADMISSION_1C = "HOSPITAL_ADMISSION_1C"
export const HIGH_RISK_BACKTERIAL_UAPATHWAY_INFECTION="HIGH_RISK_BACKTERIAL_UAPATHWAY_INFECTION"
export const ADMISSION_RECS_SECOND='ADMISSION_RECS_SECOND'

const SIXTY_ONE_NINETY = '29 - 60 Days';

export const SIXTY_NINE_NINETY_TITLE_OVERRIDES = {
  [SIXTY_ONE_NINETY_DISCLAIMER]: SIXTY_ONE_NINETY,
  [RECOMMENDED_EVALUATION]: SIXTY_ONE_NINETY,
  [DIAGNOSTIC_TEST]: SIXTY_ONE_NINETY,
  [HSV_CHECKLIST]: SIXTY_ONE_NINETY,
  [HIGH_RISK_HSV]: SIXTY_ONE_NINETY,
  [HOSPITAL_ADMISSION]: SIXTY_ONE_NINETY,
  [LOW_HSV_RISK]: SIXTY_ONE_NINETY,
  [HIGH_RISK_BACKTERIAL_INFECTION]: SIXTY_ONE_NINETY,
  [HOSPITAL_ADMISSION_RECOMMENDATION]: SIXTY_ONE_NINETY,
  [DISPOSITION_RECCOMENDATION]: SIXTY_ONE_NINETY,
  [DISCHARGE_CHECKLIST]: SIXTY_ONE_NINETY,
  [HIGH_RISK_RECOMMENDATION]: SIXTY_ONE_NINETY,
  [DISPOSITION_RECCOMENDATION_1A]: SIXTY_ONE_NINETY,
  [HOSPITAL_ADMISSION_1B]: SIXTY_ONE_NINETY,
  [HOSPITAL_ADMISSION_1D]: SIXTY_ONE_NINETY,
  [HIGH_RISK_BACTERIAL_DISPOSITION]: SIXTY_ONE_NINETY,
  [DISCHARGE_CHECKLIST_LOW_RISK]: SIXTY_ONE_NINETY,
  [HOSPITAL_ADMISSION_1C]: SIXTY_ONE_NINETY,
  [HIGH_RISK_BACKTERIAL_UAPATHWAY_INFECTION]: SIXTY_ONE_NINETY,
  [ADMISSION_RECS_SECOND]: SIXTY_ONE_NINETY
}